media:
  - name: images
    label: Images
    input: images
    output: /images
    extensions: [ png, webp, gif ]
content:
  - name: home
    label: Home
    type: file
    path: index.html
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: layout, type: string, hidden: true, default: default }
      - name: features
        label: Features
        type: object
        fields: 
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: icon, label: Icon, type: string }
      - { name: body, label: Body, type: code, options: { format: html } }
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: published, label: Published, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: _config.yml
    path: _config.yml
    type: file
  - name: components
    label: Components
    type: collection
    path: '_includes'
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - { name: body, label: Body, type: code, options: { format: html } }