media:
  - name: images
    label: Images
    input: images
    output: /images
    extensions: [ png, webp, gif, jpg, folder ]
content:
  - name: home
    label: Home
    type: file
    path: index.html
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: layout, type: string, hidden: true, default: default }
      - name: features
        label: Features
        type: object
        fields: 
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: icon, label: Icon, type: string }
      - { name: body, label: Body, type: code, options: { format: html } }
  - name: about
    label: À propos
    type: file
    path: about.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: layout, type: string, hidden: true, default: default }
      - { name: body, label: Body, type: rich-text }
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, image, tags, published, date ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: desc
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - name: tags
        label: Tags
        type: object
        fields: 
          - name: vegan
            label: vegan
            type: string
          - name: zero-dechet
            label: zéro-déchet
            type: string
          - name: seconde-main
            label: seconde-main
            type: string
          - name: reparation
            label: réparation
            type: string
      - { name: published, label: Published, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: _config.yml
    path: _config.yml
    type: file
  - name: styles
    label: Styles
    path: style.scss
    type: file