#!/bin/bash


########################################
# Pushes updates to github repository
########################################

git add .
# (1) prompt user, and read command line argument
read -p "Commit message:" answer
# (2) check input, if empty exit
if [ $choose ~= "" ] 
then
	echo "Please enter commit message.\n"
	break
fi
# (3) if not, commit & push
git commit -m $answer
git push blog master